### ISSUE TITLE
ICCV 2023 SparseBEV

### ISSUE THREAD

**Issue by MiraclesinWang** [PeterJaq/Awesome-Autonomous-Driving#1]
Hello, thanks for your great efforts of collecting papers for reference. Our paper SparseBEV[[arXiv]](https://arxiv.org/abs/2308.09244)[[github]](https://github.com/MCG-NJU/SparseBEV) has recently been accepted to ICCV 2023. Please include our paper in your list.

**Comment by PeterJaq** [comment]
Hello, I already updated the Paper List for ICCV2023, SparseBEV is in my list. Thank your efforts, and have a nice national holiday.
